language: python

# use container infra for linux
sudo: false
python:
  - 3.5
  - 2.7
  - pypy
  - pypy3
install:
  - pip install cpplint

script:
- cpplint --verbose=5 `find . -path '*' \( -name '*.h' -o -name '*.cpp' \)`